-- 코드를 입력하세요
SELECT *
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC

-- 코드를 입력하세요
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC

-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = "Sick"

-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != "Aged"

-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC

-- 코드를 입력하세요
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1

-- 코드를 입력하세요
SELECT DATETIME AS 시간
FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1

-- 코드를 입력하세요
SELECT COUNT(*) AS count
FROM ANIMAL_INS

-- 코드를 입력하세요
SELECT COUNT(DISTINCT NAME) AS count
FROM ANIMAL_INS

-- 코드를 입력하세요
SELECT ANIMAL_TYPE, COUNT(*) AS count
FROM ANIMAL_INS
WHERE ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog'
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

-- 코드를 입력하세요
SELECT NAME, COUNT(*) AS count
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING count != 1
ORDER BY NAME

-- 코드를 입력하세요
SELECT HOUR,COUNT(HOUR)
FROM(
    SELECT DATE_FORMAT(DATETIME,'%H') AS HOUR
    FROM ANIMAL_OUTS    
)A
GROUP BY HOUR
HAVING HOUR>=9 AND HOUR<20
ORDER BY HOUR ASC

-- 코드를 입력하세요
SELECT hour(datetime) HOUR, count(*) as COUNT
from animal_outs
group by hour
having hour >= 9 and hour <= 19
order by hour

-- 코드를 입력하세요
WITH RECURSIVE `HOUR_BASE` AS (
    SELECT 0 AS `HOUR`
    UNION ALL
    SELECT `HOUR`+1 FROM `HOUR_BASE` WHERE `HOUR` < 23
)
SELECT HOUR_BASE.`HOUR`, COUNT(ANIMAL_INFO.`HOUR`)
FROM (
    SELECT HOUR(DATETIME) AS `HOUR`
    FROM `ANIMAL_OUTS`
) AS `ANIMAL_INFO`
NATURAL RIGHT OUTER JOIN `HOUR_BASE`
GROUP BY `HOUR`
ORDER BY `HOUR`

-- 코드를 입력하세요
SELECT
  HOURS.HOUR, 
  IFNULL(AO.CNT, 0) AS COUNT
FROM
  JSON_TABLE(
      "[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]",
      '$[*]' COLUMNS (HOUR INT PATH '$')
  ) HOURS
 LEFT JOIN (
    SELECT 
      HOUR(DATETIME) as HOUR, 
      COUNT(*) as CNT
    FROM ANIMAL_OUTS 
    GROUP BY HOUR(DATETIME)
) AS AO ON AO.HOUR = HOURS.HOUR

-- 코드를 입력하세요
set @a := -1;
SELECT A.HOUR,IFNULL(B.COUNT,0) FROM
(SELECT @a:=@a+1 as HOUR FROM ANIMAL_OUTS) A LEFT JOIN
(SELECT HOUR(DATETIME) as HOUR,COUNT(*) as COUNT FROM ANIMAL_OUTS GROUP BY HOUR(DATETIME) ) B
ON A.HOUR = B.HOUR WHERE A.HOUR<=23

-- 코드를 입력하세요
SELECT DATETIME, count(*)-1
from (SELECT to_number(TO_CHAR ( LEVEL ))-1 as DATETIME FROM DUAL CONNECT BY LEVEL <= 24
      union all
      select to_number(TO_CHAR (DATETIME,'HH24')) from ANIMAL_OUTS) 
group by DATETIME
order by DATETIME

-- 코드를 입력하세요
WITH RECURSIVE HOUR AS(
SELECT 0 AS h
UNION ALL
SELECT h+1 FROM HOUR WHERE h<23)
SELECT h AS HOUR, COALESCE(COUNT(ANIMAL_ID),0) AS COUNT
FROM HOUR LEFT JOIN ANIMAL_OUTS ON HOUR.h = DATE_FORMAT(DATETIME, '%k')
GROUP BY HOUR.h

-- 코드를 입력하세요
